# Generated by Django 5.0.6 on 2024-05-09 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deal', models.DateTimeField(auto_now=True, verbose_name='Date deal')),
                ('asset_name', models.CharField(max_length=16, verbose_name='Криптовалюта')),
                ('asset_price', models.DecimalField(decimal_places=10, default=0, max_digits=32)),
                ('asset_amount', models.DecimalField(decimal_places=10, default=0, max_digits=32)),
                ('usd_amount', models.DecimalField(decimal_places=10, default=0, max_digits=16)),
                ('comission', models.DecimalField(decimal_places=10, default=0, max_digits=16)),
                ('trade_side', models.CharField(default='buy', max_length=4, verbose_name='Сторона сделки')),
                ('comment', models.CharField(max_length=128, verbose_name='Комментарий сделки')),
                ('exchange', models.CharField(max_length=64, verbose_name='Криптобиржа')),
                ('user_deal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_deal'],
            },
        ),
    ]
